### ISSUE TITLE
Increased support for meta-regression

### ISSUE THREAD

**Issue by jadahlke** [psychmeta/psychmeta#5]
Ideally, a meta-regression function could include these features:
- [ ] Fitting a WLS regression model -- coefficients, SEs, CIs, R^2, SDrho
- [ ] Adjusting R^2 for overfitting
- [ ] Accepting transformations of continuous moderators [e.g., age + age^2, log(income)]
- [ ] A `predict.` method to predict a mean and SD of effect sizes for a given, with CI, CV
- [ ] Artefact distribution-based corrections
- [ ] Corrections for sampling error in study-effect sizes
- [ ] Corrections for artifacts (at least reliability) in moderators

- [ ] It would be nice to simply report (and have a function for) observed and corrected (for sampling error, study-level artifacts, and moderator artifacts) effect size/moderator correlation matrices.

Variance due to moderator (including continuous):
tausq_nomods - tausq_withmods
`Q.wls.nomods <- sum(wls.nomods$weights * wls.nomods$residuals^2)`
`Q.wls.withmods <- sum(wls.withmods$weights * wls.withmods$residuals^2)`
`tausq_moderator <- `
`((Q.wls.nomods - wls.nomods$df.residual) / `
`(sum(wls.nomods $weights) - (sum(wls.nomods $weights^2)/sum(wls.nomods $weights)))) - ` `((Q.wls.withmods - wls.withmods$df.residual) / `
`(sum(wls.withmods$weights) - (sum(wls.withmods$weights^2)/sum(wls.withmods$weights))))`

Can alternatively use the H-S var_rho estimator in place of the WLS-based tausq_nomods, which let's use this approach with artifact distribution meta-analyses (with the assumptions that artifacts are uncorrelated with moderators and that residual heterogeneity is evenly distributed across the moderator range).
